//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cso.IfnsExporter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1155127")]
        public string КНД {
            get {
                return ((string)(this["КНД"]));
            }
            set {
                this["КНД"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6182")]
        public string КодНО {
            get {
                return ((string)(this["КодНО"]));
            }
            set {
                this["КодНО"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2977")]
        public int НомерТребования {
            get {
                return ((int)(this["НомерТребования"]));
            }
            set {
                this["НомерТребования"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Автономная некоммерческая организация центр социального обслуживания населения \"М" +
            "ы вместе\"")]
        public string НаимОрг {
            get {
                return ((string)(this["НаимОрг"]));
            }
            set {
                this["НаимОрг"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6155079653")]
        public string ИННЮЛ {
            get {
                return ((string)(this["ИННЮЛ"]));
            }
            set {
                this["ИННЮЛ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("615501001")]
        public string КПП {
            get {
                return ((string)(this["КПП"]));
            }
            set {
                this["КПП"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ПодписантПрПодп {
            get {
                return ((int)(this["ПодписантПрПодп"]));
            }
            set {
                this["ПодписантПрПодп"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("88636232423")]
        public string ПодписантТлф {
            get {
                return ((string)(this["ПодписантТлф"]));
            }
            set {
                this["ПодписантТлф"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Мельникова")]
        public string ПодписантФамилия {
            get {
                return ((string)(this["ПодписантФамилия"]));
            }
            set {
                this["ПодписантФамилия"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Галина")]
        public string ПодписантИмя {
            get {
                return ((string)(this["ПодписантИмя"]));
            }
            set {
                this["ПодписантИмя"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Стефановна")]
        public string ПодписантОтчество {
            get {
                return ((string)(this["ПодписантОтчество"]));
            }
            set {
                this["ПодписантОтчество"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IGOLETS-NB;Initial Catalog=cso.sk.grachev_20210527;Integrated Securit" +
            "y=False;Persist Security Info=True;Pooling=False;User ID=sa;Password=tM566658")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Реализация услуг по уходу за больными")]
        public string OperationName {
            get {
                return ((string)(this["OperationName"]));
            }
            set {
                this["OperationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string ЗаменаНомерДоговора {
            get {
                return ((string)(this["ЗаменаНомерДоговора"]));
            }
            set {
                this["ЗаменаНомерДоговора"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1010221")]
        public string КодОпер {
            get {
                return ((string)(this["КодОпер"]));
            }
            set {
                this["КодОпер"] = value;
            }
        }
    }
}
