//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Cso.IfnsExporter {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Файл {
        
        private ФайлДокумент документField;
        
        private string идФайлField;
        
        private string версПрогField;
        
        private string версФормField;
        
        /// <remarks/>
        public ФайлДокумент Документ {
            get {
                return this.документField;
            }
            set {
                this.документField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайл {
            get {
                return this.идФайлField;
            }
            set {
                this.идФайлField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсПрог {
            get {
                return this.версПрогField;
            }
            set {
                this.версПрогField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсФорм {
            get {
                return this.версФормField;
            }
            set {
                this.версФормField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокумент {
        
        private ФайлДокументСвНП свНПField;
        
        private ФайлДокументПодписант подписантField;
        
        private ФайлДокументРеестрДокПОбНЛ[] реестрДокПОбНЛField;
        
        private string имяФайлТребField;
        
        private string кНДField;
        
        private string датаДокField;
        
        private string кодНОField;
        
        private ФайлДокументПериод периодField;
        
        private bool периодFieldSpecified;
        
        private string отчетГодField;
        
        private string номКоррField;
        
        /// <remarks/>
        public ФайлДокументСвНП СвНП {
            get {
                return this.свНПField;
            }
            set {
                this.свНПField = value;
            }
        }
        
        /// <remarks/>
        public ФайлДокументПодписант Подписант {
            get {
                return this.подписантField;
            }
            set {
                this.подписантField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("РеестрДокПОбНЛ")]
        public ФайлДокументРеестрДокПОбНЛ[] РеестрДокПОбНЛ {
            get {
                return this.реестрДокПОбНЛField;
            }
            set {
                this.реестрДокПОбНЛField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИмяФайлТреб {
            get {
                return this.имяФайлТребField;
            }
            set {
                this.имяФайлТребField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КНД {
            get {
                return this.кНДField;
            }
            set {
                this.кНДField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаДок {
            get {
                return this.датаДокField;
            }
            set {
                this.датаДокField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодНО {
            get {
                return this.кодНОField;
            }
            set {
                this.кодНОField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументПериод Период {
            get {
                return this.периодField;
            }
            set {
                this.периодField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ПериодSpecified {
            get {
                return this.периодFieldSpecified;
            }
            set {
                this.периодFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОтчетГод {
            get {
                return this.отчетГодField;
            }
            set {
                this.отчетГодField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string НомКорр {
            get {
                return this.номКоррField;
            }
            set {
                this.номКоррField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвНП {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НПФЛ", typeof(ФайлДокументСвНПНПФЛ))]
        [System.Xml.Serialization.XmlElementAttribute("НПЮЛ", typeof(ФайлДокументСвНПНПЮЛ))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвНПНПФЛ {
        
        private ФайлДокументСвНПНПФЛФИО фИОField;
        
        private string иННФЛField;
        
        /// <remarks/>
        public ФайлДокументСвНПНПФЛФИО ФИО {
            get {
                return this.фИОField;
            }
            set {
                this.фИОField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ {
            get {
                return this.иННФЛField;
            }
            set {
                this.иННФЛField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвНПНПФЛФИО {
        
        private string фамилияField;
        
        private string имяField;
        
        private string отчествоField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Фамилия {
            get {
                return this.фамилияField;
            }
            set {
                this.фамилияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Имя {
            get {
                return this.имяField;
            }
            set {
                this.имяField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Отчество {
            get {
                return this.отчествоField;
            }
            set {
                this.отчествоField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвНПНПЮЛ {
        
        private ФайлДокументСвНПНПЮЛСвРеоргЮЛ свРеоргЮЛField;
        
        private string наимОргField;
        
        private string иННЮЛField;
        
        private string кППField;
        
        /// <remarks/>
        public ФайлДокументСвНПНПЮЛСвРеоргЮЛ СвРеоргЮЛ {
            get {
                return this.свРеоргЮЛField;
            }
            set {
                this.свРеоргЮЛField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг {
            get {
                return this.наимОргField;
            }
            set {
                this.наимОргField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ {
            get {
                return this.иННЮЛField;
            }
            set {
                this.иННЮЛField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП {
            get {
                return this.кППField;
            }
            set {
                this.кППField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументСвНПНПЮЛСвРеоргЮЛ {
        
        private ФайлДокументСвНПНПЮЛСвРеоргЮЛФормРеорг формРеоргField;
        
        private string иННЮЛField;
        
        private string кППField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументСвНПНПЮЛСвРеоргЮЛФормРеорг ФормРеорг {
            get {
                return this.формРеоргField;
            }
            set {
                this.формРеоргField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ {
            get {
                return this.иННЮЛField;
            }
            set {
                this.иННЮЛField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП {
            get {
                return this.кППField;
            }
            set {
                this.кППField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументСвНПНПЮЛСвРеоргЮЛФормРеорг {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументПодписант {
        
        private ФайлДокументПодписантФИО фИОField;
        
        private ФайлДокументПодписантСвПред свПредField;
        
        private ФайлДокументПодписантПрПодп прПодпField;
        
        private string тлфField;
        
        /// <remarks/>
        public ФайлДокументПодписантФИО ФИО {
            get {
                return this.фИОField;
            }
            set {
                this.фИОField = value;
            }
        }
        
        /// <remarks/>
        public ФайлДокументПодписантСвПред СвПред {
            get {
                return this.свПредField;
            }
            set {
                this.свПредField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументПодписантПрПодп ПрПодп {
            get {
                return this.прПодпField;
            }
            set {
                this.прПодпField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Тлф {
            get {
                return this.тлфField;
            }
            set {
                this.тлфField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументПодписантФИО {
        
        private string фамилияField;
        
        private string имяField;
        
        private string отчествоField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Фамилия {
            get {
                return this.фамилияField;
            }
            set {
                this.фамилияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Имя {
            get {
                return this.имяField;
            }
            set {
                this.имяField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Отчество {
            get {
                return this.отчествоField;
            }
            set {
                this.отчествоField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументПодписантСвПред {
        
        private string наимДокField;
        
        private string наимОргField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДок {
            get {
                return this.наимДокField;
            }
            set {
                this.наимДокField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг {
            get {
                return this.наимОргField;
            }
            set {
                this.наимОргField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументПодписантПрПодп {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументРеестрДокПОбНЛ {
        
        private ФайлДокументРеестрДокПОбНЛСведВидОпер[] сведВидОперField;
        
        private string номРеестрField;
        
        private string кодОперField;
        
        private decimal общСтНеоблОпВсField;
        
        private decimal общСтТовВсField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведВидОпер")]
        public ФайлДокументРеестрДокПОбНЛСведВидОпер[] СведВидОпер {
            get {
                return this.сведВидОперField;
            }
            set {
                this.сведВидОперField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string НомРеестр {
            get {
                return this.номРеестрField;
            }
            set {
                this.номРеестрField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодОпер {
            get {
                return this.кодОперField;
            }
            set {
                this.кодОперField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ОбщСтНеоблОпВс {
            get {
                return this.общСтНеоблОпВсField;
            }
            set {
                this.общСтНеоблОпВсField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ОбщСтТовВс {
            get {
                return this.общСтТовВсField;
            }
            set {
                this.общСтТовВсField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументРеестрДокПОбНЛСведВидОпер {
        
        private ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДог[] предТипДогField;
        
        private string номСвВидОпField;
        
        private string видОперField;
        
        private decimal общСтНеоблОпField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПредТипДог")]
        public ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДог[] ПредТипДог {
            get {
                return this.предТипДогField;
            }
            set {
                this.предТипДогField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string НомСвВидОп {
            get {
                return this.номСвВидОпField;
            }
            set {
                this.номСвВидОпField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВидОпер {
            get {
                return this.видОперField;
            }
            set {
                this.видОперField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ОбщСтНеоблОп {
            get {
                return this.общСтНеоблОпField;
            }
            set {
                this.общСтНеоблОпField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДог {
        
        private ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДогСведКАгент[] сведКАгентField;
        
        private string номТипДогField;
        
        private string имяФайлДогField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведКАгент")]
        public ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДогСведКАгент[] СведКАгент {
            get {
                return this.сведКАгентField;
            }
            set {
                this.сведКАгентField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string НомТипДог {
            get {
                return this.номТипДогField;
            }
            set {
                this.номТипДогField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИмяФайлДог {
            get {
                return this.имяФайлДогField;
            }
            set {
                this.имяФайлДогField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДогСведКАгент {
        
        private object itemField;
        
        private ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДогСведКАгентДокПОбНЛ[] докПОбНЛField;
        
        private decimal общСтТовField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведОрг", typeof(ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДогСведКАгентСведОрг))]
        [System.Xml.Serialization.XmlElementAttribute("СведФЛ", typeof(ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДогСведКАгентСведФЛ))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДокПОбНЛ")]
        public ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДогСведКАгентДокПОбНЛ[] ДокПОбНЛ {
            get {
                return this.докПОбНЛField;
            }
            set {
                this.докПОбНЛField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ОбщСтТов {
            get {
                return this.общСтТовField;
            }
            set {
                this.общСтТовField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДогСведКАгентСведОрг {
        
        private string наимОргField;
        
        private string иННЮЛField;
        
        private string кППField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг {
            get {
                return this.наимОргField;
            }
            set {
                this.наимОргField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ {
            get {
                return this.иННЮЛField;
            }
            set {
                this.иННЮЛField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП {
            get {
                return this.кППField;
            }
            set {
                this.кППField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДогСведКАгентСведФЛ {
        
        private ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДогСведКАгентСведФЛФИО фИОField;
        
        private string иННФЛField;
        
        /// <remarks/>
        public ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДогСведКАгентСведФЛФИО ФИО {
            get {
                return this.фИОField;
            }
            set {
                this.фИОField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ {
            get {
                return this.иННФЛField;
            }
            set {
                this.иННФЛField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДогСведКАгентСведФЛФИО {
        
        private string фамилияField;
        
        private string имяField;
        
        private string отчествоField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Фамилия {
            get {
                return this.фамилияField;
            }
            set {
                this.фамилияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Имя {
            get {
                return this.имяField;
            }
            set {
                this.имяField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Отчество {
            get {
                return this.отчествоField;
            }
            set {
                this.отчествоField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ФайлДокументРеестрДокПОбНЛСведВидОперПредТипДогСведКАгентДокПОбНЛ {
        
        private string видДокField;
        
        private string номДокField;
        
        private string датаДокField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВидДок {
            get {
                return this.видДокField;
            }
            set {
                this.видДокField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомДок {
            get {
                return this.номДокField;
            }
            set {
                this.номДокField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаДок {
            get {
                return this.датаДокField;
            }
            set {
                this.датаДокField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ФайлДокументПериод {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("56")]
        Item56,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("55")]
        Item55,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("54")]
        Item54,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("51")]
        Item51,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("24")]
        Item24,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("22")]
        Item22,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
    }
}
